### ISSUE TITLE
Pyllola input

### ISSUE THREAD

**Issue by mone27** [Draio/Python-ABC#1]
Nella pyllola input alla fine ci sta questa frase:
```
Importante: input() restituisce una stringa! Se si vuole utilizzare il dato come se fosse un numero, ad esempio, è necessario convertire il risultato da stringa ad un formato numerico.
```
Che secondo me è molto utile perché da principiante non sai dove mettere le mani se devi prendere un numero.
Però proporrei per essere più chiaro
"È necessario convertire il risultato da stringa ad un formato numerico. Si può usare la funzione int() o float().
Esempio
```
numero_intero = int(input("inserisci un numero intero))
```
"

**Comment by Ardius** [comment]
Ciao, grazie per il consiglio, che ne dici di qualcosa tipo:

---

La funzione input() restituisce sempre un una stringa, se si vuole utilizzare il risultato come dato numerico  è necessario convertirlo utilizzando le funzioni [int() o float()](Pyllole/Type_Number.md).

    >>> stringa = input("Inserisci un numero intero: ")                                  
    Inserisci un numero intero: 42
    >>> numero=int(stringa)
  
Se la stringa passata a int() non è convertibile in un intero, Python genererà un'errore, è quindi consigliabile gestire l'eccezione con [try/except](Pyllole/Try_Except.md)

    stringa = input("Inserisci un numero intero: ")                                                     
    try:
         numero=int(stringa)
    except:
        print("Il dato inserito non è un numero intero")

Infine, è possibile racchiudere il tutto in un [ciclo](Pyllole/Loops.md) per ripetere la domanda finché il dato non sarà inserito correttamente.
Nel seguente esempio ripetiamo la richiesta finché a "numero" non viene assegnato un valore.

    numero=None                                                                                                      
    while not numero:
        try:
                  numero=int(input("Inserisci un numero intero: "))
        except:
            print("Il dato inserito non è un numero intero")

**Comment by mone27** [comment]
Secondo me mettere la gestione degli errori all'inizio può essere fuorviante per uno che ha appena iniziato.
Quindi metterei una frase del tipo
```
Se non viene inserito un numero python  genera un eccezione (link a documentazione per gestione errori)
```

**Comment by Ardius** [comment]
Sì, un po' il dubbio che sia "troppo" ce l'ho anche io.
Magari quei due esempi li metto proprio come esempi nella sezione try/except

**Comment by mone27** [comment]
Si mi sembra una buona idea, a quel punto con il link della pagina gestione errori mette una sezione apposta con input così se sei all'inizio non ti spaventi se vuoi qualcosa di più avanzato cambia solo un click

**Comment by Ardius** [comment]
Ho aggiornato le pagine Input, Try/Except e Cicli. 
Nella pagina di input c'é descritto come convertire, c'é la nota relativa alla gestione degli errori e due link ad esempi pratici in try/except e cicli.
In try/except c'é l'esempio pratico basato su input.
In cicli c'é l'esempio pratico del while utilizzato per riproporre input() in caso di errore.
